### ISSUE TITLE
Muting the outputs (via the CLI using the tmo command or by config) results in faulty behavior

### ISSUE THREAD

**Issue by shinelikethesun** [atorger/brutefir#1]
Hello Anders,

First of all, thank you for continuing to maintain brutefir. I really appreciate it.

I'd like to report a bug that occurs with (at least two) different USB interfaces and affects muting individual channels via config or the CLI. The issue is not new to version 1.1.0; it also occurs in earlier versions.

I have attached an example configuration. (The issue also occurs with a “real” configuration.)

For illustration, I included a screenshot on startup and for each mute command — tmo 0 through tmo 9 — showing the behavior.

What I did:

nc localhost 3000

tmo 0 (mute) -> took a picture -> tmo 0 (unmute)
tmo 1 (mute) -> took a picture -> tmo 1 (unmute)
..... an so on

As you can see, the selected channel is muted (from left to right 0-10), but some of the other channels are affected as well. When playing music, muting one channel may produce weird noise on another channel.

Also happens when using e.g. :  "mute: true,false,false,false,false,false,false,false,false,false;" in output section.

The sound interfaces used are a MOTU Ultralite MK5 and an RME UFX+, both in class-compliant mode.

Best regards,

Björn

Linux brutefir 6.12.56-v8-rt+ #1917 SMP PREEMPT_RT Thu Oct 30 17:38:05 GMT 2025 aarch64 GNU/Linux
Debian GNU/Linux 13 (trixie)
Advanced Linux Sound Architecture Driver Version k6.12.56-v8-rt+.

[192000motu-mute-issue.txt](https://github.com/user-attachments/files/24035624/192000motu-mute-issue.txt)

![Image](https://github.com/user-attachments/assets/1012c9e7-3fec-41bc-9f2a-4d67f084b6ad)
![Image](https://github.com/user-attachments/assets/294e51ce-a50a-4772-9b8d-fab4e9e5a740)
![Image](https://github.com/user-attachments/assets/371e177c-f99d-4b9b-b09b-3519078757e6)
![Image](https://github.com/user-attachments/assets/4feb2b5b-9f0c-424e-929b-da7d0fb25964)
![Image](https://github.com/user-attachments/assets/c567c7ed-a5f5-4270-9440-f400e608a54a)
![Image](https://github.com/user-attachments/assets/e0a8fe9e-41c1-4479-a725-afaa32a03774)
![Image](https://github.com/user-attachments/assets/bf67236f-3015-4a63-852f-8dd7dcc12f74)
![Image](https://github.com/user-attachments/assets/bc06d699-a364-40d7-9bb1-1267954f55d2)
![Image](https://github.com/user-attachments/assets/65aff807-8bb4-44cc-838e-6c636e8e6dd1)
![Image](https://github.com/user-attachments/assets/78b25634-c08e-4475-890e-fcc98db301eb)
![Image](https://github.com/user-attachments/assets/03ae20d8-36cc-46cd-bd0c-a1ca7689ca08)

**Comment by atorger** [comment]
I haven't had time to look into this yet. But maybe you could try using

	device: "alsa" { device: "hw:3"; access: "rw_noninterleaved"; };
or
	device: "alsa" { device: "hw:3"; access: "mmap_noninterleaved"; };

if the driver accepts that. Muting takes place in the raw converted output buffers just before being sent to the sound card (that's why peak values 'ppk' does not show any effect of muted output channels).

Per default the device is opened in interleaved mode, meaning all channel samples are interleaved, and with a 3 byte sample size it's a bit messy to mute so could be some bug in that code.

I don't have much sound hardware in my computer these days so I cannot test with exactly the same stuff you have, but I'll have a look into the mute code and see if I can find any bug.

If you run the above test with non-interleaved buffers (the access setting in the alsa I/O module is new for 1.1.0), please report the result. If it's still the same behavior the problem is probably somewhere else than the mute code.

**Comment by atorger** [comment]
Didn't require much time to find an issue. Line 335 in dai.c, can you add "3 *", as shown in the patch below recompile and do a test? It should then work in the default interleaved mode. 

The bug is that in interleaved mode and 3 byte sample format (S24_LE) the mute function steps only one byte between channels instead of 3. (The same type of loop works for the other sample format sizes as then the data type is the same type as the sample, so the bug is limited to 24 bit sample formats)

```
diff --git a/src/dai.c b/src/dai.c
index 13b9c86..3354186 100644
--- a/src/dai.c
+++ b/src/dai.c
@@ -332,7 +332,7 @@ do_mute(struct subdev *sd,
         }
         break;
     case 3:
-        for (uint8_t *p = &buf->u8[mid_offset]; p < endp; p += sd->channels.open_channels) {
+        for (uint8_t *p = &buf->u8[mid_offset]; p < endp; p += 3 * sd->channels.open_channels) {
             for (int n = 0; n < n_mute; n++) {
                 p[bsch[n]+0] = 0;
                 p[bsch[n]+1] = 0;

```

**Comment by atorger** [comment]
I did not have much to test with as said, but confident enough in the fix I have pushed the fix and made a v1.1.1 release. Let me know if it works, then we can close this issue.

**Comment by shinelikethesun** [comment]
Hello Anders,

thank you for your efforts in analyzing the problem. I’ve just tested the new version 1.1.1, but unfortunately the issue is still present on both interfaces (MOTU + RME).

Your suggestion to try different access methods also fails:

```
ALSA I/O: Could not set audio output parameters for "hw:3":
  Failed to set forced access mode to RW_NONINTERLEAVED: Invalid argument.
  Device supports: MMAP_INTERLEAVED RW_INTERLEAVED
```

I tested the supported modes as well. For example, muting via `tmo 1` again leads to “weird noise” on channels that aren’t involved.

If there’s anything I can do to help with further debugging, just let me know.

Best regards,
Björn

**Comment by shinelikethesun** [comment]
Hello again,

I just took a look at the code in dai.c. Could it be that a break is missing at the end of case 3? I can only verify it on the live system tonight.

Best regards,

Björn

**Comment by shinelikethesun** [comment]
Hi Anders,

it seems your patch, along with the missing "break", fixes the issue.

Muting works as expected now.

Best regards,

Björn

**Comment by atorger** [comment]
Argghh missing break, a classic, thanks for spotting. Made a v1.1.2 release with the fix. Closing this issue now.
